# Generated by Django 3.2 on 2021-11-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(default='car model', max_length=50, verbose_name='Модель автомобиля')),
                ('price', models.IntegerField(verbose_name='Стоимость аренды')),
                ('photo_url', models.TextField(default='photo_url', verbose_name='photo')),
                ('car_description', models.TextField(default='car description', verbose_name='url')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.brand')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('mail', models.CharField(max_length=100, verbose_name='e-mail')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.car')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderstatus')),
                ('user_id', models.ForeignKey(default='user id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.user')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='color_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.color'),
        ),
    ]
