# Generated by Django 3.2 on 2021-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='Имя пользователя', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='user_phone',
            field=models.CharField(default='Телефон', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(default='car description', verbose_name='description_car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo_url',
            field=models.TextField(default='photo_url', verbose_name='photo_url'),
        ),
    ]
