# Generated by Django 3.2 on 2021-11-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.orderstatus'),
        ),
    ]
