# Generated by Django 3.2 on 2021-11-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
